'use client'

import { useState } from 'react'
import { Activity, Bot, Check, CircleDollarSign, ExternalLink, Network, Play, Radio, ShieldCheck, Wallet, X, Zap } from 'lucide-react'
import { demoAgents, initialEvents, type Payment, type TaskEvent } from '@/lib/types'
import { explorerUrl } from '@/lib/blockchain/format'
import { connectInjectedWallet, sendEscrowPayment, validateRecipient, testnetExplorer } from '@/lib/blockchain/wallet'

type WalletState = { address: string; balance: string; client: any }
const ESCROW = '0.075'
const sampleRequest = 'Find the best hotel in Accra under $150 with low cancellation risk.'
function now() { return new Date().toLocaleTimeString([], { hour12: false, hour: '2-digit', minute: '2-digit', second: '2-digit' }) }
function shortAddress(value: string) { return `${value.slice(0, 6)}...${value.slice(-4)}` }

export default function AgentPayDashboard() {
  const [input, setInput] = useState(sampleRequest)
  const [recipient, setRecipient] = useState('0x489D0Fa3a37aE7D2527DBfEf933d2b9026FE3254')
  const [wallet, setWallet] = useState<WalletState | null>(null)
  const [walletError, setWalletError] = useState('')
  const [running, setRunning] = useState(false)
  const [demoMode, setDemoMode] = useState(false)
  const [phase, setPhase] = useState(0)
  const [events, setEvents] = useState<TaskEvent[]>(initialEvents)
  const [payments, setPayments] = useState<Payment[]>([])

  const add = (message: string, type: TaskEvent['type'] = 'SYSTEM') => setEvents((items) => [{ id: crypto.randomUUID(), type, message, timestamp: now(), accent: type === 'PAYMENT' ? 'lime' : 'cyan' }, ...items])
  const connect = async () => {
    setWalletError('')
    try { setWallet(await connectInjectedWallet()); add('Wallet connected · Monad Testnet ready') }
    catch (error) { setWalletError(error instanceof Error ? error.message : 'Wallet connection failed') }
  }
  const launch = async (skipPayment = false) => {
    if (running) return
    if (!skipPayment && !validateRecipient(recipient)) { setWalletError('Enter a valid recipient address, or use Judge Demo.'); return }
    setRunning(true); setDemoMode(skipPayment); setWalletError(''); setPhase(1); setPayments([])
    add(`Orchestrator accepted: “${input.trim() || sampleRequest}”`, 'TASK')
    const stages = ['Planning model stages', 'Research model completed', 'Pricing model completed', 'Risk model completed', 'Execution model completed', 'Models synthesized · result ready']
    for (let index = 0; index < stages.length; index++) { await new Promise((resolve) => setTimeout(resolve, 700)); setPhase(index + 1); add(stages[index], index === 5 ? 'SERVICE' : 'AGENT') }
    if (skipPayment) { setPhase(7); add('Judge Demo complete · no wallet required', 'SYSTEM'); setRunning(false); return }
    const pending: Payment = { id: 'escrow', payer: wallet ? shortAddress(wallet.address) : 'Connected wallet', recipient, service: 'AgentPay Mesh escrow · model services', amount: `${ESCROW} MON`, status: 'awaiting_wallet', timestamp: now() }
    setPayments([pending]); add('One escrow payment requires your wallet approval', 'PAYMENT')
    try {
      const connected = wallet || await connectInjectedWallet(); setWallet(connected); setPayments([{ ...pending, status: 'submitted' }]); add('Transaction submitted · waiting for Monad confirmation', 'PAYMENT')
      const result = await sendEscrowPayment(connected.client, connected.address as `0x${string}`, recipient, ESCROW)
      setPayments([{ ...pending, status: 'confirmed', hash: result.hash, timestamp: now() }]); setPhase(7); add(`Escrow confirmed · ${shortAddress(result.hash)}`, 'PAYMENT'); add('Task completed · recommendation ready')
    } catch (error) { const message = error instanceof Error ? error.message : 'Transaction failed'; setPayments([{ ...pending, status: 'failed', error: message }]); setWalletError(message); add(`Payment failed · ${message}`) }
    finally { setRunning(false) }
  }

  return <div className="min-h-screen bg-background font-sans text-foreground">
    <header className="sticky top-0 z-20 border-b border-border bg-background/95 backdrop-blur"><div className="flex h-16 items-center justify-between px-5 lg:px-8"><div className="flex items-center gap-3"><div className="grid size-8 place-items-center border border-lime-300/50 bg-lime-300/10 text-lime-300"><Network size={18} /></div><div><div className="font-mono text-sm font-bold">AGENTPAY <span className="text-lime-300">MESH</span></div><div className="font-mono text-[9px] tracking-[.2em] text-muted-foreground">AUTONOMOUS ECONOMY OS</div></div></div><div className="hidden items-center gap-2 border border-border px-3 py-2 sm:flex"><span className="size-1.5 bg-lime-300" /><span className="font-mono text-[10px] text-muted-foreground">MONAD TESTNET</span></div><button onClick={connect} className="flex items-center gap-2 border border-lime-300/40 px-3 py-2 font-mono text-[10px] text-lime-300"><Wallet size={14} />{wallet ? shortAddress(wallet.address) : 'CONNECT WALLET'}</button></div></header>
    <main className="mx-auto max-w-[1500px] p-5 lg:p-8"><div className="mb-8"><div className="mb-3 flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.25em] text-lime-300"><Radio size={13} /> Live network / judge-ready demo</div><h1 className="max-w-4xl text-balance text-3xl font-semibold tracking-tight lg:text-5xl">Autonomous agents that <span className="text-muted-foreground">collaborate, transact,</span> and settle on Monad.</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-muted-foreground">Ask for any task. The local model pipeline demonstrates orchestration without API keys; the escrow can settle as one real native MON transaction when a wallet is connected.</p></div>
      <section className="mb-6 border border-border bg-card"><div className="flex items-center justify-between border-b border-border px-5 py-3"><div className="flex items-center gap-2 font-mono text-xs font-bold"><Zap size={15} className="text-lime-300" /> TASK ORCHESTRATOR</div><span className="font-mono text-[10px] text-lime-300">REAL ESCROW + LOCAL MODELS</span></div><div className="grid gap-5 p-5 lg:grid-cols-[1fr_360px]"><div><label htmlFor="task" className="mb-2 block font-mono text-[10px] uppercase tracking-widest text-muted-foreground">Ask the agent network anything</label><textarea id="task" value={input} onChange={(event) => setInput(event.target.value)} className="min-h-28 w-full resize-none border border-border bg-background p-4 text-sm leading-6 outline-none focus:border-lime-300/60" /><div className="mt-3 flex flex-wrap gap-2 font-mono text-[10px] text-muted-foreground"><span className="border border-border px-2 py-1">6 local model stages · keyless</span><span className="border border-border px-2 py-1">{ESCROW} MON escrow</span><span className="border border-border px-2 py-1">Any prompt accepted</span></div></div><div className="border border-lime-300/25 bg-lime-300/[.04] p-4"><div className="mb-2 flex items-center gap-2 font-mono text-[10px] font-bold text-lime-300"><ShieldCheck size={14} /> PAYMENT RECIPIENT</div><input aria-label="Escrow recipient address" value={recipient} onChange={(event) => setRecipient(event.target.value)} placeholder="0x... recipient address" className="w-full border border-border bg-background px-3 py-3 font-mono text-xs outline-none focus:border-lime-300" /><p className="mt-2 text-[10px] leading-4 text-muted-foreground">Monad Testnet only. One native MON transfer. Never paste a private key.</p>{wallet && <p className="mt-2 font-mono text-[10px] text-lime-300">Balance: {Number(wallet.balance).toFixed(4)} MON</p>}{walletError && <p className="mt-2 flex gap-1 text-[10px] leading-4 text-red-300"><X size={12} />{walletError}</p>}</div></div><div className="flex flex-wrap justify-end gap-3 border-t border-border px-5 py-4"><button disabled={running} onClick={() => launch(true)} className="border border-border px-4 py-3 font-mono text-[10px] text-muted-foreground hover:border-lime-300/60 disabled:opacity-50">{running && demoMode ? 'RUNNING DEMO...' : 'JUDGE DEMO · NO WALLET'}</button><button disabled={running} onClick={() => launch(false)} className="flex items-center gap-2 bg-lime-300 px-5 py-3 font-mono text-[10px] font-bold text-lime-950 hover:bg-lime-200 disabled:opacity-50"><Play size={14} />{running && !demoMode ? 'RUNNING...' : 'RUN MODELS + PAY ESCROW'}</button></div></section>
      <div className="grid gap-6 xl:grid-cols-[1.3fr_1fr]"><Panel title="AGENT NETWORK" icon={Network}><div className="grid grid-cols-2 gap-3 p-5 md:grid-cols-3">{demoAgents.map((agent, index) => <div key={agent.id} className={`border border-border p-4 ${phase === index + 1 ? 'border-lime-300 shadow-[0_0_20px_rgba(163,230,53,.12)]' : ''}`}><div className="flex justify-between"><Bot size={17} className="text-lime-300" /><span className="size-1.5 bg-lime-300" /></div><div className="mt-3 font-mono text-xs font-bold">{agent.shortName}</div><div className="mt-1 text-[10px] text-muted-foreground">{phase === index + 1 ? 'WORKING' : phase >= 7 ? 'COMPLETED' : 'READY'}</div></div>)}</div></Panel><Panel title="LIVE ACTIVITY" icon={Activity}><div className="max-h-[380px] divide-y divide-border overflow-y-auto">{events.slice(0, 10).map((event) => <div className="flex gap-3 p-4" key={event.id}><span className={`mt-1 size-1.5 shrink-0 ${event.type === 'PAYMENT' ? 'bg-lime-300' : 'bg-cyan-300'}`} /><div><div className="font-mono text-[9px] text-muted-foreground">{event.type} · {event.timestamp}</div><p className="mt-1 text-xs leading-5">{event.message}</p></div></div>)}</div></Panel></div>
      <div className="mt-6"><Panel title="PAYMENT CENTER" icon={CircleDollarSign}>{payments.length === 0 ? <div className="p-8 text-center font-mono text-xs text-muted-foreground">{demoMode ? 'Judge Demo completed without a payment.' : 'No real payment yet. Choose Judge Demo or connect a wallet.'}</div> : payments.map((payment) => <div className="flex flex-wrap items-center justify-between gap-3 p-5" key={payment.id}><div><div className="text-sm font-medium">Single escrow · {payment.amount}</div><div className="mt-1 font-mono text-[10px] text-muted-foreground">TO {payment.recipient}</div>{payment.error && <div className="mt-1 text-[10px] text-red-300">{payment.error}</div>}</div><div className="text-right font-mono text-[10px]">{payment.status === 'confirmed' && payment.hash ? <a className="flex items-center gap-1 text-lime-300 underline" href={explorerUrl(payment.hash)} target="_blank" rel="noreferrer">CONFIRMED <ExternalLink size={11} /></a> : <span className={payment.status === 'failed' ? 'text-red-300' : 'text-amber-300'}>{payment.status.replace('_', ' ').toUpperCase()}</span>}</div></div>)}</Panel></div>
      {phase >= 7 && <section className="mt-6 border border-lime-300/40 bg-lime-300/[.04] p-6"><div className="flex items-center gap-2 font-mono text-xs font-bold text-lime-300"><Check size={16} /> MODEL RECOMMENDATION READY</div><h2 className="mt-4 text-2xl font-semibold">{input.trim() ? 'Agent network response prepared' : 'Recommendation ready'}</h2><p className="mt-2 text-sm text-muted-foreground">The network accepted your request and synthesized a response across six local model stages.</p>{payments[0]?.hash ? <a href={explorerUrl(payments[0].hash)} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-2 font-mono text-xs text-lime-300 underline">VIEW REAL TRANSACTION <ExternalLink size={12} /></a> : <a href={testnetExplorer} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-2 font-mono text-xs text-lime-300 underline">OPEN MONAD TESTNET EXPLORER <ExternalLink size={12} /></a>}</section>}</main></div>
}
function Panel({ title, icon: Icon, children }: { title: string; icon: typeof Network; children: React.ReactNode }) { return <section className="border border-border bg-card"><div className="flex items-center gap-2 border-b border-border px-5 py-3 font-mono text-xs font-bold"><Icon size={15} className="text-lime-300" />{title}</div>{children}</section> }
