export type AgentStatus = 'idle' | 'planning' | 'working' | 'waiting' | 'paid' | 'completed'
export type TaskStatus = 'pending' | 'planning' | 'running' | 'completed' | 'failed'
export type PaymentStatus = 'pending' | 'awaiting_wallet' | 'submitted' | 'confirmed' | 'failed'
export interface Agent { id:string; name:string; shortName:string; description:string; capabilities:string[]; walletAddress:string; pricePerTask:string; status:AgentStatus; completed:number; earned:string; spent:string; color:string }
export interface Subtask { id:string; label:string; agentId:string; status:'pending'|'running'|'completed'; detail:string; payment?:string }
export interface Payment { id:string; payer:string; recipient:string; service:string; amount:string; status:PaymentStatus; hash?:string; timestamp:string; error?:string }
export interface TaskEvent { id:string; type:'TASK'|'AGENT'|'PAYMENT'|'SERVICE'|'SYSTEM'; message:string; timestamp:string; accent:string }
export interface DemoState { taskStatus:TaskStatus; phase:number; activeAgent?:string; subtasks:Subtask[]; payments:Payment[]; events:TaskEvent[]; completed:boolean }
export const demoAgents:Agent[]=[
{id:'orchestrator',name:'Orchestrator Agent',shortName:'Orchestrator',description:'Coordinates the agent economy and delegates work.',capabilities:['Task planning','Delegation'],walletAddress:'0x4A2f...91C0',pricePerTask:'—',status:'planning',completed:38,earned:'0.00',spent:'0.00',color:'cyan'},
{id:'research',name:'Research Agent',shortName:'Research',description:'Finds and ranks options from trusted sources.',capabilities:['Web research','Reviews'],walletAddress:'0x2B8e...4F71',pricePerTask:'0.025 MON',status:'idle',completed:124,earned:'1.84',spent:'0.42',color:'blue'},
{id:'pricing',name:'Pricing Agent',shortName:'Pricing',description:'Compares live market prices and value.',capabilities:['Price comparison','Market analysis'],walletAddress:'0x71cA...A92F',pricePerTask:'0.020 MON',status:'idle',completed:89,earned:'1.78',spent:'0.31',color:'lime'},
{id:'risk',name:'Risk Agent',shortName:'Risk',description:'Evaluates cancellation and seller reliability.',capabilities:['Risk scoring','Policy analysis'],walletAddress:'0x9d12...7B3E',pricePerTask:'0.015 MON',status:'idle',completed:76,earned:'1.14',spent:'0.22',color:'amber'},
{id:'execution',name:'Execution Agent',shortName:'Execution',description:'Verifies availability and prepares the action.',capabilities:['Availability','Booking prep'],walletAddress:'0xF03a...28D4',pricePerTask:'0.015 MON',status:'idle',completed:61,earned:'0.91',spent:'0.19',color:'purple'},
{id:'reporting',name:'Reporting Agent',shortName:'Reporting',description:'Synthesizes agent outputs into a clear answer.',capabilities:['Synthesis','Recommendations'],walletAddress:'0xC82d...E610',pricePerTask:'0.010 MON',status:'idle',completed:142,earned:'1.42',spent:'0.36',color:'pink'}]
export const initialSubtasks:Subtask[]=[{id:'research',label:'Discover hotels in Accra',agentId:'research',status:'pending',detail:'Search trusted travel sources'},{id:'pricing',label:'Compare nightly rates',agentId:'pricing',status:'pending',detail:'Find best value under $150',payment:'0.020 MON'},{id:'risk',label:'Analyze cancellation risk',agentId:'risk',status:'pending',detail:'Score policies and reliability',payment:'0.015 MON'},{id:'execution',label:'Verify availability',agentId:'execution',status:'pending',detail:'Check dates and inventory',payment:'0.015 MON'},{id:'reporting',label:'Produce recommendation',agentId:'reporting',status:'pending',detail:'Synthesize all agent outputs',payment:'0.010 MON'}]
export const initialEvents:TaskEvent[]=[{id:'welcome',type:'SYSTEM',message:'Mesh online · model stages ready',timestamp:'12:41:58',accent:'muted'}]
export const initialPayments:Payment[]=[]
